apiVersion: cluster.palette.m.crossplane.io/v1alpha1
kind: ConfigTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: cluster/v1alpha1/configtemplate
  labels:
    testing.upbound.io/example-name: basic_template
  name: basic-template
  namespace: upbound-system
spec:
  forProvider:
    cloudType: aws
    clusterProfile:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: infra_profile
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: addon_profile
    context: project
    description: Basic AWS cluster configuration template
    name: basic-aws-template
    tags:
    - env:production
    - team:platform
